#!/usr/bin/env python3
"""Fetch polygenic risk score weights from PGS Catalog FTP.

Downloads harmonized GRCh38 scoring files for curated PGS IDs and outputs
data/seed/prs_weights.tsv.

Source: PGS Catalog (https://www.pgscatalog.org/)
Data license: CC BY 4.0 (https://www.pgscatalog.org/about/#terms_of_use)

Supports optional per-score variant trimming: set max_variants in PGS_SCORES
to keep only the top N variants by |weight| for large scores. Currently all
curated scores use None (no trimming) as the selected scores are small enough.
"""

import csv
import gzip
import io
import sys
import urllib.request
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_DEFAULT_SEED_DIR = _REPO_ROOT / "data" / "seed"

# PGS IDs to fetch: (pgs_id, trait_name, max_variants or None for all)
# All scores must have permissive licenses (CC BY 4.0 or equivalent).
# See docs/licenses.md for per-score citation requirements.
PGS_SCORES = [
    ("PGS000010", "Coronary artery disease", None),
    ("PGS000349", "Coronary artery disease", None),
    ("PGS000074", "Colorectal cancer", None),
    ("PGS002251", "Body mass index (BMI)", None),
]

FTP_PATTERN = (
    "https://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/{pgs_id}/"
    "ScoringFiles/Harmonized/{pgs_id}_hmPOS_GRCh38.txt.gz"
)


def download_scoring_file(pgs_id: str) -> str:
    """Download and decompress a PGS Catalog harmonized scoring file."""
    url = FTP_PATTERN.format(pgs_id=pgs_id)
    print(f"  Downloading {url}...")
    req = urllib.request.Request(url)
    with urllib.request.urlopen(req, timeout=120) as resp:
        compressed = resp.read()
    return gzip.decompress(compressed).decode("utf-8")


def parse_scoring_file(
    content: str, pgs_id: str, trait: str, max_variants: int | None
) -> list[dict]:
    """Parse a PGS Catalog scoring file into prs_weights rows.

    Harmonized files have columns like:
    chr_name, chr_position, effect_allele, other_allele,
    effect_weight, hm_rsID, hm_chr, hm_pos, ...
    """
    # Skip header comment lines
    lines = []
    for line in content.split("\n"):
        if line.startswith("#"):
            continue
        lines.append(line)

    reader = csv.DictReader(io.StringIO("\n".join(lines)), delimiter="\t")

    rows = []
    for row in reader:
        # Use harmonized columns (hm_*) when available, fall back to original
        rsid = row.get("hm_rsID") or row.get("rsID") or ""
        chrom = row.get("hm_chr") or row.get("chr_name") or ""
        pos = row.get("hm_pos") or row.get("chr_position") or ""
        effect_allele = row.get("effect_allele") or ""
        weight = row.get("effect_weight") or ""

        # Skip rows with missing essential data
        if not rsid or not chrom or not pos or not weight:
            continue

        # Skip non-standard chromosomes
        if not (chrom.isdigit() or chrom in ("X", "Y", "MT")):
            continue

        # Add chr prefix
        if not chrom.startswith("chr"):
            chrom = f"chr{chrom}"

        try:
            weight_f = float(weight)
            pos_i = int(pos)
        except (ValueError, TypeError):
            continue

        rows.append(
            {
                "prs_id": pgs_id,
                "trait": trait,
                "rsid": rsid,
                "chrom": chrom,
                "pos": pos_i,
                "effect_allele": effect_allele,
                "weight": weight_f,
            }
        )

    # If max_variants set, keep top N by |weight|
    if max_variants and len(rows) > max_variants:
        rows.sort(key=lambda r: abs(r["weight"]), reverse=True)
        print(f"    Trimmed from {len(rows)} to top {max_variants} by |weight|")
        rows = rows[:max_variants]

    return rows


def main(output_dir: Path | None = None):
    output_dir = output_dir or _DEFAULT_SEED_DIR
    all_rows = []

    for pgs_id, trait, max_variants in PGS_SCORES:
        print(f"\n{pgs_id}: {trait}")
        try:
            content = download_scoring_file(pgs_id)
        except Exception as e:
            print(f"  ERROR: Failed to download {pgs_id}: {e}")
            return 1

        rows = parse_scoring_file(content, pgs_id, trait, max_variants)
        print(f"  Parsed {len(rows)} variants")
        all_rows.extend(rows)

    # Sort by prs_id, then chrom/pos
    chrom_order = {f"chr{i}": i for i in range(1, 23)}
    chrom_order.update({"chrX": 23, "chrY": 24})
    all_rows.sort(
        key=lambda r: (r["prs_id"], chrom_order.get(r["chrom"], 99), r["pos"])
    )

    # Write output
    output_path = output_dir / "prs_weights.tsv"
    fieldnames = [
        "prs_id",
        "trait",
        "rsid",
        "chrom",
        "pos",
        "effect_allele",
        "weight",
    ]
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        f.write(
            "# Source: PGS Catalog (https://www.pgscatalog.org/). "
            "Auto-generated by fetch_prs_data.py.\n"
        )
        writer = csv.DictWriter(
            f, fieldnames=fieldnames, delimiter="\t", lineterminator="\n"
        )
        writer.writeheader()
        for row in all_rows:
            writer.writerow(row)

    print(f"\nWrote {len(all_rows)} PRS weights to {output_path.name}")
    return 0


if __name__ == "__main__":
    _dir = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    sys.exit(main(output_dir=_dir))
